# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
