# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexo', '0002_auto_20170219_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='is_site_generated',
            field=models.BooleanField(default=False),
        ),
    ]
