# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexo', '0003_googleuser_is_site_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='guser_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
